name: Test

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_test:
    name: Unit Test
    runs-on: macos-14
    env:
      DEVELOPER_DIR: "/Applications/Xcode_15.4.app/Contents/Developer"
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Run Tests
        run: |
          xcodebuild test \
            -project Examples/Examples.xcodeproj \
            -scheme Examples \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=17.5" \
            -resultBundlePath TestResults/result_bundle

      - name: Archive test results
        if: success() || failure()
        uses: kishikawakatsumi/xcresulttool@2b37f116695328d5e503ac8dadca0f1545a51da4 #v1.7.1
        with:
          path: TestResults/result_bundle.xcresult
          show-passed-tests: false
